import sharp from "sharp";
import { describe, expect, it } from "vitest";
import { readImageDimensions } from "@/lib/uploads/read-image-dimensions";

async function createImage(
  format: "jpeg" | "png" | "webp",
  width: number,
  height: number
) {
  const image = sharp({
    create: {
      width,
      height,
      channels: 3,
      background: { r: 32, g: 96, b: 160 }
    }
  });

  return new Uint8Array(await image.toFormat(format).toBuffer());
}

function createWebpChunk(type: "VP8L" | "VP8X", data: number[]) {
  const chunkSize = data.length;
  const totalSize = 12 + 8 + chunkSize + (chunkSize % 2);
  const bytes = new Uint8Array(totalSize);
  const view = new DataView(bytes.buffer);
  bytes.set(new TextEncoder().encode("RIFF"), 0);
  view.setUint32(4, totalSize - 8, true);
  bytes.set(new TextEncoder().encode("WEBP"), 8);
  bytes.set(new TextEncoder().encode(type), 12);
  view.setUint32(16, chunkSize, true);
  bytes.set(data, 20);
  return bytes;
}

describe("reference image header preflight", () => {
  it("reads PNG dimensions without decoding its pixels", async () => {
    const image = await createImage("png", 37, 23);

    await expect(readImageDimensions(image)).resolves.toEqual({
      format: "png",
      width: 37,
      height: 23
    });
  });

  it("reads JPEG dimensions from a browser Blob", async () => {
    const image = await createImage("jpeg", 41, 29);

    await expect(readImageDimensions(new Blob([image]))).resolves.toEqual({
      format: "jpeg",
      width: 41,
      height: 29
    });
  });

  it("reads a lossy WebP frame generated by Sharp", async () => {
    const image = await createImage("webp", 43, 31);

    await expect(readImageDimensions(image)).resolves.toEqual({
      format: "webp",
      width: 43,
      height: 31
    });
  });

  it("reads WebP VP8L packed dimensions", async () => {
    const widthMinusOne = 320;
    const heightMinusOne = 198;
    const image = createWebpChunk("VP8L", [
      0x2f,
      widthMinusOne & 0xff,
      ((widthMinusOne >> 8) & 0x3f) | ((heightMinusOne & 0x03) << 6),
      (heightMinusOne >> 2) & 0xff,
      (heightMinusOne >> 10) & 0x0f
    ]);

    await expect(readImageDimensions(image)).resolves.toEqual({
      format: "webp",
      width: 321,
      height: 199
    });
  });

  it("reads WebP VP8X canvas dimensions", async () => {
    const image = createWebpChunk("VP8X", [
      0, 0, 0, 0,
      0x7f, 0x02, 0,
      0x67, 0x01, 0
    ]);

    await expect(readImageDimensions(image)).resolves.toEqual({
      format: "webp",
      width: 640,
      height: 360
    });
  });

  it("rejects invalid and truncated encoded inputs", async () => {
    const results = await Promise.allSettled([
      readImageDimensions(new Uint8Array([1, 2, 3, 4])),
      readImageDimensions(new Uint8Array([0xff, 0xd8, 0xff])),
      readImageDimensions(
        new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10, 0, 0])
      )
    ]);

    expect(results.map((result) => result.status)).toEqual([
      "rejected",
      "rejected",
      "rejected"
    ]);
  });
});
